### PR TITLE
Addition of the citation

### PR DESCRIPTION
**Pull request by davebulaval**
Proposition of an official citation and addition of an _how to cite_ section.

Capture du 2019-03-15 15-12-29

### CODE REVIEW

**Comment by freud14** [comment]
In the name of the reference, my name should not have a "c".

**Comment by davebulaval** [comment]
Correction made.

**Comment by freud14** [comment]
Can you also add this to the homepage of the docs?

**Comment by davebulaval** [comment]
Yes, I will later on.

**Pull request merged**
